//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MotherTravel.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonaFiscal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PersonaFiscal()
        {
            this.Factura = new HashSet<Factura>();
            this.Factura1 = new HashSet<Factura>();
        }
    
        public int idPersona { get; set; }
        public string nombre { get; set; }
        public string apellido { get; set; }
        public string rfc { get; set; }
        public string razon_social { get; set; }
        public string direccion { get; set; }
        public string fecha_nacimiento { get; set; }
        public string telefono { get; set; }
        public string email { get; set; }
        public string categoria { get; set; }
        public string tipo_persona { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Factura> Factura { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Factura> Factura1 { get; set; }
    }
}
